apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: christian-boar-nodejs 
  janus-idp.io/tekton: christian-boar-nodejs
  backstage.io/kubernetes-id: christian-boar-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: christian-boar-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  